# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

broad_types = BroadType.create([{name: 'Mortal'}, {name: 'Goodneighbor'}, {name: 'Wyrd'}, {name: 'Undead'}])

powers = Power.create([
		{name: 'Accurate [Weapon]', tier: 1, description: 'Choose a weapon when selecting this power. Your character gains a free retest when using this weapon. This power can be taken multiple times, choosing a different weapon each time.', requires_specification: true, specification_name: 'Weapon', select_multiple: true},
		{name: 'Animal Conversation', tier: 1, description: 'Your character can spend a Spirit to be able to speak to a type of animal for a scene, chosen when they activate this power.'},
		{name: '[Animal] Form', tier: 2, description: 'Your character can shapeshift into the form of a specific animal, chosen when you take this power. Doing so takes some time, but it can be sped up by spending spirit. For the cost of 1 Spirit it can happen in a combat action and for 2 Spirit it can happen reflexively. While you remain an animal, treat the type (Wolf, Bat, etc.) as your Approach for the purpose of retests. Shapeshifting back can happen in a combat action, or reflexively for 1 Spirit. This power can be taken multiple times, choosing a different animal each time.', requires_specification: true, specification_name: 'Animal', select_multiple: true},
		{name: 'Armor', tier: 1, description: 'Your character can mystically increase their toughness. They can spend a Spirit to gain 3 temporary Stress boxes for a scene as an action. These Stress boxes do not automatically regenerate at the end of the scene, and if lost the character cannot just get them back by activating this power again. If the character Regenerates, the power’s Stress boxes return.'},
		{name: 'Attuned [Item]', tier: 1, description: 'Choose a specific item when you take this power. Your character can spend 1 Spirit to summon this item to their hands. This power can be taken multiple times, choosing a different item each time.', requires_specification: true, specification_name: 'Item', select_multiple: true},
		{name: 'Blessing', tier: 1, description: 'Your character can spend 2 Spirit to “gift” a retest to someone else. Each character can only store one of these retests at a time, and can “spend” it to retest any challenge. They go away after a day.'},
		{name: 'Blend In', tier: 1, description: 'Your character can spend a Spirit to appear just like a unremarkable person for a scene. They can interact with objects and people but if they draw attention to themselves (attack a player or use an power) their disguise breaks. They cannot use this power if someone is actively engaging with them, but can use the power for a retest on some stealth conflicts.'},
		{name: 'Blood Magic', tier: 2, description: 'Your character can harm themselves (or others) for power. By spending a Spirit and taking 1 point of damage, they can receive a retest on any test. In addition, they can spend 1 Spirit and use the blood of themselves or others in a lengthy ceremony to fuel rituals.'},
		{name: 'Charm [Type]', tier: 1, description: 'Choose a Broad Type when selecting this power. Your character can spend a Spirit to try to make that Broad Type your friend for a scene. This power can be taken up to four times, once for each type.', requires_specification: true, specification_name: 'Type', select_multiple: true},
		{name: 'Dodge', tier: 1, description: 'Your character can spend a Spirit to cancel one attack’s damage or effect.'},
		{name: 'Eidetic Memory', tier: 1, description: 'Your character has a free retest whenever trying to memorize or remember something.'},
		{name: '[Element] Control', tier: 2, description: 'Choose a type of element when you select this power. Your character can attempt to control it. In addition, you may spend a Spirit to attempt to increase or reduce the amount of this element in an area or to retest your power to control it.', requires_specification: true, specification_name: 'Element', select_multiple: true},
		{name: '[Element] Creation', tier: 1, description: 'Choose a type of element when you select this power. Your character can spend a Spirit to create this element out of thin air in their hands, but only enough to fill a pair of cupped hands. This element can be thrown as an attack, but then more would need to be created.', requires_specification: true, specification_name: 'Element', select_multiple: true},
		{name: 'Elusive', tier: 1, description: 'Your character can spend a Spirit to retest against someone affecting them with mystical or magical Powers.'},
		{name: 'Empathic', tier: 2, description: 'Your character can attempt to read the emotions of others. They can also spend a Spirit to attempt to intensify or reduce that emotion.'},
		{name: 'Endurance', tier: 1, description: 'Gain a Stress box. In addition, your character can spend a Spirit for a retest when dealing with poisons, diseases, or other physical health concerns. This power can be taken up to three times, but note that you only benefit from the extra Stress boxes.', requires_specification: false, select_multiple: true, select_max: 3},
		{name: 'Fleetness', tier: 2, description: 'Your character can move at double the speed of others and always goes in the first Initiative group. In addition, you may spend a Spirit to have extreme speed. This allows your character to move apparently supernaturally, allowing them to run as fast as a car or give a retest when unnatural speed would be applicable.'},
		{name: 'Flight', tier: 2, description: 'Spend a Spirit to be able to fly for a scene. You move at regular speed, but can spend a Spirit to move at triple speed or gain a retest to remain flying.'},
		{name: 'Focused', tier: 1, description: 'Your character can spend a Spirit to get a second retest from your Approach when it applies.'},
		{name: 'Forge', tier: 1, description: 'Your character can spend a Spirit to be able to manipulate an object with magic, either building or disassembling something with no apparent tools. You can spend up to 2 more Spirit when using this power to increase the speed at which this power works.'},
		{name: 'Honed Sense', tier: 1, description: 'Choose one of your character’s basic senses (taste, smell, touch, hearing, sight). When using that sense, your character receives a free retest. Your character can take this power up to five times, each time choosing a different basic sense.', requires_specification: true, specification_name: 'Sense', select_multiple: true, select_max: 5},
		{name: 'Hypnotise', tier: 1, description: 'Spend a Spirit to try to force someone to mindlessly obey what you say for a scene. They get a chance to regain control if your commands would cause them harm or do harm to others. You can only Hypnotise one person at a time.'},
		{name: 'Illusions', tier: 2, description: 'Your character can spend a Spirit to attempt to make believable illusions. These illusions cannot harm others and your character can not directly control or change the illusion once they have been made.'},
		{name: 'Intangibility', tier: 2, description: 'Your character can spend a Spirit to be able to float and pass through objects. They must spend a Spirit to end this effect, which is otherwise permanent. They cannot interact with the physical world at all in this state, but can be effected by magic.'},
		{name: 'Invisibility', tier: 2, description: 'Your character can spend a Spirit to attempt to go entirely Invisible. If your character attacks someone or benefits from another power, this effect ends immediately.'},
		{name: 'Lucky', tier: 1, description: 'Once per game, your character can spend a Spirit to retest any one challenge.'},
		{name: 'Mystical Sight', tier: 1, description: 'Your character can spend a Spirit to attempt to pierce illusions and see magical energy.'},
		{name: 'Plant Control', tier: 1, description: 'Your character can spend a Spirit to attempt to direct a single plant he can see. Your character can cause it move, grow, or wither. Your character may also spend a Spirit to be able to converse with Plants for the scene.'},
		{name: 'Puissance', tier: 2, description: 'Your character deals an extra point of damage with melee attacks on a win. In addition, you may spend a Spirit to perform feats of strength. This allows your character to pick up small cars and throw them or give a retest when these big muscles would be applicable.'},
		{name: 'Ritual Magic', tier: 2, description: 'Your character can use and create mystical rituals. By spending 2 Spirit and performing a lengthy ceremony, you can imbue power into a ritual. RULES TEXT FOR HOW RITUALS WORK, THEY COST 1BP EACH WITH 1 FREE'},
		{name: 'Self Healing', tier: 1, description: 'Your character can spend an amount of Spirit to heal the same amount of damage as an action.'},
		{name: 'Doppelganger', tier: 2, description: 'You can spend 2 Spirit to shapeshift into another person (attempt for a specific person). This does not give you any more abilities or special powers, even if you appear to be something power. While active, you can get a free retest from this power when deceiving others with your new form.'},
		{name: 'Technological Adept', tier: 1, description: 'You get a free retest when operating advanced technology. In addition, you can spend a Spirit to attempt to control or sabotage technology from a distance.'},
		{name: 'Telekinesis', tier: 1, description: 'You can spend a Spirit to be able to attempt to move objects with your mind for a scene. Your character cannot move anything much more than 10 pounds, and not with any amount of dexterity. You can take this power up to 3 times. The second time it allows you to move things up to 50 pounds and the third time you can move things up to 100 pounds or things up to 10 pounds dexterously.'},
		{name: 'Unkillable', tier: 1, description: 'If your character becomes Incapacitated, they do not bleed out or die.  Each unkillable character must pick a specific weakness, however. You die if that weakness is exploited on you when you are Incapacitated.', requires_specification: true, specification_name: 'Weakness', select_multiple: false},
		{name: 'Weather Control', tier: 1, description: 'Your character can spend a Spirit to attempt to affect the weather in the local area. Your character must be able to see the sky, and must perform a ritual or extended action related to their Role that lasts at least 1 minute. Your character can either intensify the current weather, cause it to rain/snow, roll in fog, and warm or cool the temperature.'}
	])

#remove some of these later once we prune down the list
approaches = Approach.create([
		{name: "Adventurous"},
		{name: "Aggressive"},
		{name: "Analytical"},
		{name: "Bold"},
		{name: "Broad"},
		{name: "Careful"},
		{name: "Cautious"},
		{name: "Cheerful"},
		{name: "Clever"},
		{name: "Competitor"},
		{name: "Cruel"},
		{name: "Curious"},
		{name: "Defiant"},
		{name: "Direct"},
		{name: "Elegant"},
		{name: "Efficient"},
		{name: "Flashy"},
		{name: "Forceful"},
		{name: "Graceful"},
		{name: "Hasty"},
		{name: "Helpful"},
		{name: "Honest"},
		{name: "Intense"},
		{name: "Independent"},
		{name: "Just"},
		{name: "Kind"},
		{name: "Lawful"},
		{name: "Loving"},
		{name: "Loud"},
		{name: "Mindful"},
		{name: "Mysterious"},
		{name: "Narrow"},
		{name: "Obedient"},
		{name: "Objective"},
		{name: "Open-minded"},
		{name: "Patient"},
		{name: "Perfectionist"},
		{name: "Polite"},
		{name: "Professional"},
		{name: "Puckish"},
		{name: "Quick"},
		{name: "Reckless"},
		{name: "Rough"},
		{name: "Self-Serving"},
		{name: "Smooth"},
		{name: "Sneaky"},
		{name: "Subtle"},
		{name: "Tenacious"},
		{name: "Thorough"},
		{name: "Thoughtful"},
		{name: "Treacherous"},
		{name: "Underhanded"},
		{name: "Unpredictable"},
		{name: "Unwavering"},
		{name: "Vengeful"},
		{name: "Violent"},
		{name: "Wise"},
		{name: "Zealous"}
	])